server {
    listen       80;
    listen  [::]:80;
    server_name  geunh.com localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Enable compression
    gzip on;
    gzip_types text/plain text/css application/javascript image/svg+xml;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

server {
    listen       80;
    listen  [::]:80;
    server_name  www.geunh.com;

    return 302 https://geunh.com/;
}

server {
    listen       80 default_server;
    listen  [::]:80 default_server;
    server_name  _;

    return 302 https://geunh.com/?from_nopage=1;
}
