name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          set -e
          docker compose up -d --pull always --remove-orphans

      - name: Prune unused Docker data
        run: |
          set -e
          docker builder prune -f
          docker image prune -f
